conf:
  backup:
    dossier_sauv: /home/administrateur/sauvegarde_db
    backup_dir_web: /home/administrateur/sauvegarde_web
    retention: 7
    ip_sauv_dist: 192.168.0.3
sites:
  site1:
    mysql:
      host: localhost
      user: administrateur
      passwd: 123456
      db: wordpress
    web:
      racine: /var/www
  site2:
    mysql:
      host: localhost
      user: root
      passwd: 123456
      db: test2
    web:
      racine: /var/www
  site3:
    mysql:
      host: localhost
      user: root
      passwd: 123456
      db: test3
    web:
      racine: /var/www
